### PR TITLE
[added] automated release tools

### LINKED ISSUE #4: Automated Release
Alright so for automated release, in other projects I've been using
- https://www.npmjs.com/package/mt-changelog for the changelog
- https://www.npmjs.com/package/release-script for automated release

The changelog obliges you to normalize the commit messages with tags in order to generate nice changelog, but that's not a bad thing I guess! This is how changelog will look like https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md

Tags are added, fixed, changed, removed.

release-script enables you to do

```
release --patch
release --minor
release --major
```

Which will automatically bump the version, commit, tag and publish to npm directly.

If that's ok with you I can include them. If not we can find another solution.

### PR DESCRIPTION
**Pull request by dozoisch**
closes #4 

Alright I've added commands in the package.json to use the release tool.

 It works with the latest git tags and generates the changelog from the prefixes
- `[added]` added a new feature
- `[changed]` changed an existing feature
- `[fixed]` fixed a bug
- `[removed]` removed something or a file

So to do the first generation, you have to tag the last release as a starting point. To tag 2.0.2:

`git tag v2.0.2 1d0079da891a2056697ae549a7b87992c53030d5`

Then you can run npm run patch/minor depending on the one you want.

You can try it without publishing by doing `npm run path -- --dry-run` (need both `--`). This will do all the steps without pushing/publishing. It'll just echo the commands instead.

Right now the bundle is not generated from `npm run build`, so you might want to add it. I removed the pre-publish, since the release tool runs this:

```
npm run test
npm run build
```

### CODE REVIEW

**Comment by tnrich** [comment]
I'm a little confused about how the git tag functionality works. I ran the command you suggested from my shell and got this: 

```
$ git tag v2.0.2 1d0079da891a2056697ae549a7b87992c53030d5
fatal: tag 'v2.0.2' already exists
$ git tag
v0.1.1
v0.2.0
v1.0.0
v1.0.1
v2.0.0
v2.0.1
v2.0.2
```

Is that what I should expect to see?

**Comment by dozoisch** [comment]
Ohhh ! I thought there were no tags on the repo, but it seems it's because you never pushed the tags!

do `git push --tags` , then you should be able to go to next step directly (`npm run <patch or minor>`)

Tags are only pushed when you explicitely push them.

**Comment by tnrich** [comment]
Okay, I pushed the tags, and then did a dry run, and then actually ran the patch script:

```
$ npm run patch

> react-variable-height-infinite-scroller@2.0.2 patch /Users/tnrich/Sites/react-variable-height-infinite-scroller
> release patch

No pending changes
Current with latest changes from remote
Running: linting and tests
Completed: linting and tests
Version changed from 2.0.2 to 2.0.3
Running: build
Completed: build
Generated Changelog
Tagging: v2.0.3
Tagged: v2.0.3
Releasing: npm package
Released: npm package
The "bowerRepo" is not set in package.json. Not publishing bower.
Version v2.0.3 released!
```

**Comment by dozoisch** [comment]
Seems like everything worked :) I can see the package on npm, and thats are on github also!

**Comment by tnrich** [comment]
Yup, it looks good. Now we should probably manually test that the build
still works and that there were no breaking changes. And, in the future
perhaps add a bit of automated testing.

**Comment by dozoisch** [comment]
Yes! I tested the build earlier in my project and it seemed fine! But indeed some automated testing would be the best

**Comment by tnrich** [comment]
Nice work, thanks for all the tooling you’ve integrated into this.
Hopefully it should make building and contributing easier.

**Pull request merged**
